#Prima tipologia di scope: statico e dinamico
#es1
x = 5
f = fun() { x }
x = 99
f()

scope statico: f() -> 5
scope dinamico: f() -> 99

#es2
a = 1
g = fun() { a + 1 }
let a = 10 in g()

scope statico: g() -> 1 + 1 -> 2
scope dinamico: g() -> 10 + 1 -> 11



#es3
x = 10
f = fun(n) { x = x + n; x }
g = fun()  { let x = 0 in f(5) }
f(1) + g()

esecuzione scope statico:
f(1) -> x = 11 -> 11
g() -> f(5) -> x = 11+5 -> 16
f(1) + g() -> 11 + 16 -> 27

esecuzione scope dinamico:
f(1) -> x = 11 -> 11
g() -> f(5) -> x = 0+5 -> 5
f(1) + g() -> 11 + 5 -> 16


#es4
x = 1
f = fun() { x }
g = fun() { let x = 2 in f() }
h = fun() { let x = 3 in g() }
h()

esecuzione scope statico:
h()-> g() -> f() -> 1
esecuzione scope dinamico:
h()-> g() -> f() -> 2


#Seconda tipologia di scope: Record di Attivazione e Display
#es1

program = Let('x', Num(10),
           Let('f', Fun(['a'], BinOp('+', Var('a'), Var('x'))),
            Call(FunName('f'), [Num(5)])))

Interpreter(scoping='static', passing='value', show_ar=True).run(program)

x=10
f = fun(a) { a + x }
f(5)

Quanti AR vengono stampati? 1
Qual è la variabile locale nell AR? a = 5
Verso quale ambiente punta lo static link? ambiente globale (main non correttissimo)
'
╔═ Record di Attivazione ══════════════════════════════════╗
║  call frame (a)   [profondità lessicale: 1]              ║
╠══════════════════════════════════════════════════════════╣
║  variabili locali:                                       ║
║    a = 5                                                 ║
╠══════════════════════════════════════════════════════════╣
║  static link  → [let f]  ...  {x=10, f=<fun(a)>}         ║
║  dynamic link → [Ambiente globale]  (chiamante)          ║
╚══════════════════════════════════════════════════════════╝
'

#es2

program = Let('x', Num(1),
           Let('f', Fun(['a'],
                   Let('y', Num(2),
                       BinOp('+', Var('a'), Var('y')))),
            Let('g', Fun([],
                    Call(FunName('f'), [Num(10)])),
             Call(FunName('g'), []))))


depth	AR corrente	contenuto
0	    ?	        ?
1	    ?	        ?
2	    ?	        ?


x=1
f = fun(a) { y = 2, a + y }
g = fun() { f(10) }
g()



'
╔═ Record di Attivazione g ════════════════════════════════╗
║  call frame ()   [profondità lessicale: 1]               ║
╠══════════════════════════════════════════════════════════╣
║  variabili locali:                                       ║
║    ∅                                                     ║
╠══════════════════════════════════════════════════════════╣
║  static link  → [globale]  depth=0                       ║
║  dynamic link → [Ambiente globale] depth=0 (chiamante)   ║
╚══════════════════════════════════════════════════════════╝
'

'
╔═ Record di Attivazione f ════════════════════════════════╗
║  call frame ()   [profondità lessicale: 1]               ║
╠══════════════════════════════════════════════════════════╣
║  variabili locali:                                       ║
║      a = 10, y = 2                                       ║
╠══════════════════════════════════════════════════════════╣
║  static link  → [Ambiente globale] depth=0               ║
║  dynamic link → [record g] depth=1     (chiamante)       ║
╚══════════════════════════════════════════════════════════╝
'

depth	AR corrente	        contenuto
0	    Ambiente globale	x=1, f=<fun(a)>, g=<fun>
1	    call frame g()      ∅
2	    call frame f(10)    a=10



#es3

program = Let('x', Num(1),
           Let('f', Fun([], Var('x')),
            Let('g', Fun([],
                    Let('x', Num(99),
                        Call(FunName('f'), []))),
             Call(FunName('g'), []))))


Il static link di f cambia tra i due scoping? Perché?
Cambia perché con lo scope statico f() punta all'ambiente globale, mentre con lo scope dinamico f() punta all'ambiente di g() che è il chiamante di f().
Il dynamic link cambia? Perché? No perché il chiamante di f() è sempre g() in entrambi i casi.
Quale scoping produce il risultato 1? Quale produce 99? Lo scope statico produce 1, mentre lo scope dinamico produce 99.


x=1
f = fun() { x }
g = fun() { x = 99, f() }
g()


'
╔═ Record di Attivazione g ════════════════════════════════╗
║  call frame ()   [profondità lessicale: 1]               ║
╠══════════════════════════════════════════════════════════╣
║  variabili locali:                                       ║
║    ∅                                                     ║
╠══════════════════════════════════════════════════════════╣
║  static link  → [globale]  depth=0                       ║
║  dynamic link → [Ambiente globale] depth=0 (chiamante)   ║
╚══════════════════════════════════════════════════════════╝
'

'
╔═ Record di Attivazione f ════════════════════════════════╗
║  call frame ()   [profondità lessicale: 1]               ║
╠══════════════════════════════════════════════════════════╣
║  variabili locali:                                       ║
║      x = 1  static, x = 99  dynamic                      ║
╠══════════════════════════════════════════════════════════╣
║  static link  → [Ambiente globale] depth=0               ║
║  dynamic link → [record g] depth=1     (chiamante)       ║
╚══════════════════════════════════════════════════════════╝
'



#es4

program = Let('x', Num(0),
           Let('f', Fun(['n'],
                   BinOp('+', Var('n'), Var('x'))),
            Let('g', Fun(['m'],
                    Call(FunName('f'), [BinOp('*', Var('m'), Num(2))])),
             Let('h', Fun([],
                     Call(FunName('g'), [Num(5)])),
              Call(FunName('h'), [])))))


Quante chiamate di funzione avvengono in totale? 3
Qual è la profondità massima nel Display? 2, parte da 0
Disegna il Display al momento della chiamata a f.
Qual è il risultato finale? 10

x=0
f = fun(n) { n + x }
g = fun(m) { f(m*2) }
h = fun() { g(5) }
h()

'
╔═ Record di Attivazione h ════════════════════════════════╗
║  call frame ()   [profondità lessicale: 1]               ║
╠══════════════════════════════════════════════════════════╣
║  variabili locali:                                       ║
║    ∅                                                     ║
╠══════════════════════════════════════════════════════════╣
║  static link  → [globale]  depth=0                       ║
║  dynamic link → [Ambiente globale] depth=0 (chiamante)   ║
╚══════════════════════════════════════════════════════════╝
'

'
╔═ Record di Attivazione g ════════════════════════════════╗
║  call frame (m)   [profondità lessicale: 1]              ║
╠══════════════════════════════════════════════════════════╣
║  variabili locali:                                       ║
║      m = 5                                               ║
╠══════════════════════════════════════════════════════════╣
║  static link  → [Ambiente globale] depth=0               ║
║  dynamic link → [record h] depth=1     (chiamante)       ║
╚══════════════════════════════════════════════════════════╝
'

'
╔═ Record di Attivazione f ════════════════════════════════╗
║  call frame (n)   [profondità lessicale: 1]              ║
╠══════════════════════════════════════════════════════════╣
║  variabili locali:                                       ║
║      n = 10                                              ║
╠══════════════════════════════════════════════════════════╣
║  static link  → [Ambiente globale] depth=0               ║
║  dynamic link → [record g] depth=2     (chiamante)       ║
╚══════════════════════════════════════════════════════════╝
'