#Prima tipologia . Scoping avanzato
#es1
x = 1
func inner(n) { x + n }
func outer(m) { x = 10, inner(m) }
outer(5)

scope statico: outer(5) -> x = 10, inner(5) -> x = 1 + 5 -> 6
scope dinamico: outer(5) -> x = 10, inner(5) -> x = 10 + 5 -> 15






















#es2
x = 1
func f()  { x * 2 }
func g()  { x = 5, f() }
func h()  { x = 10, g() }
h()

scope statico: x = 1, h() -> x = 10, g() -> x = 5, f() -> 1*2 = 2
scope dinamico: x = 1, h() -> x = 10, g() -> x = 5, f() -> 5*2 = 10



#es3
x = 10
func f() { x }
func g() { x = 0; f() + f() }
g()

esecuzione scope statico: x = 10, g() -> x = 0, f() -> x = 10, f() -> x = 10, 10+10 = 20

esecuzione scope dinamico: x = 10, g() -> x = 0, f() -> x = 0, f() -> x = 0, 0+0 = 0



#es4
x = 1
func f() { x }
func h() { x = 100, f() }
f() + h() + f()

esecuzione scope statico: x = 1, f() -> x = 1, h() -> x = 100, f() -> x = 1, 1+1+1 = 3

esecuzione scope dinamico: x = 1, f() -> x = 1, h() -> x = 100, f() -> x = 100, 1+100+1 = 102




#Seconda tipologia di esercizi: Passaggio parametri
#es1

x = 3
func inc(n) { n = n + 1 }
inc(x)
x

Prevedi il valore finale di x con passaggio per valore, per riferimento e per nome.

passaggio per valore: x = 3

passaggio per riferimento: x = 4

passaggio per nome: x = 3 







#es2

a = 10
b = 20
func f(x) { x = x + b }
f(a)
a


passaggio per valore: a = 10

passaggio per riferimento: a = 30

passaggio per nome: a = 10








#es3

n = 5
func f(x) { n = 0, x }
f(n * 10)


passaggio per valore: return 50

passaggio per riferimento: N/D

passaggio per nome: return 0






#es4

count = 0
func tick()  { count = count + 1, count }
func g(x)    { x + x + x }
g(tick())


Prevedi il risultato con passaggio per valore e per nome. Quante volte viene chiamata tick() in ciascun caso?

passaggio per valore: return 3, tick() chiamata 1 volta

passaggio per nome: return 6, tick() chiamata 3 volte

#es5

a = 5
func f(x, y) { x = x + 1, y = y + 1, x + y }
f(a, a)

Prevedi il valore restituito da f(a, a) con passaggio per valore, per riferimento e per nome.
Attenzione: a viene passata due volte come argomento.


passaggio per valore:  5+1=6, 5+1=6, 6+6=12, return 12

passaggio per riferimento: 5+1=6, 6+1=7, 7+7=14, return 14

passaggio per nome: 5+1=6, 5+1=6, 6+6=12, return 12

#es6

count = 0
func step()    { count = count + 1, count }
func h(a, b)   { a * b + a }
h(step(), step())

Prevedi il risultato con passaggio per valore e per nome. Quante volte viene chiamata step() in ciascun caso? In quale ordine?

passaggio per valore: 0+1 = 1, 1+1 = 2, h(1,2) -> 1*2+1=3, return 3, chiamata 2 volte

passaggio per nome: h(step(),step()) -> [step()->(0+1=1)]->1*[step()->(1+1=2)]->2+[step()->(2+1=3)]->3=5, return 5, chiamata 3 volte